---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: backend
    app: go-dep
  name: go-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      app: goserver
  strategy: {}
  template:
    metadata:
      labels:
        app: goserver
        tier: backend
    spec:
      containers:
        - image: arnavneo/goserver:1.0
          name: go-server-container
          ports:
            - name: http-go
              containerPort: 1234
          env:
            - name: PORT
              value: '1234'
          envFrom:
            - secretRef:
                name: goenv
...