---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: backend
    app: goserver
  name: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      app: goserver
  strategy: {}
  template:
    metadata:
      labels:
        app: goserver
        tier: backend
    spec:
      containers:
        - image: arnavneo/goserver:1.0
          name: goserver
          ports:
            - name: http
              containerPort: 1234
          env:
            - name: PORT
              value: '1234'
#          env:
#            - name: MONGODB_URI
#              value: mongodb+srv://arnav:urlshortener@cluster0.8hlrx0u.mongodb.net/?retryWrites=true&w=majority
#
#            - name: REDIS_URI
#              value: redis-11430.c11.us-east-1-3.ec2.cloud.redislabs.com:11430
#
#            - name: REDIS_PASS
#              value: w5YyVU0mFDLdUvZAsYTH8Ex6FnGV1XBk
#
#            - name: DATABASE_NAME
#              value: user_db
#
#            - name: DATABASE_COLLECTION
#              value: user_db_urlshortener
#
#
#            - name: SECRET
#              value: sdfs651df15sd41f15ds1f5ds1f5sd1ffwerf1dss1f55ef69
#
#            - name: ORIGINS
#              value: http://localhost:3000
          envFrom:
            - secretRef:
                name: goenv
          resources: {}
status: {}
...