apiVersion: v1
kind: Service
metadata:
  name: ejs-service
spec:
  selector:
    app: ejserver
    tier: backend
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
  type: NodePort
  