---
apiVersion: v1
kind: Service
metadata:
  name: ejs-svc
  labels:
    app: ejs-svc
spec:
  selector:
    app: ejserver
    tier: backend
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
  type: ClusterIP
...