apiVersion: v1
kind: Service
metadata:
  name: go-svc
  labels:
    app: go-svc
spec:
  selector:
    app: goserver
    tier: backend
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
  type: LoadBalancer
  