---
- 
  hosts: localhost_group
  connection: local 
  become: yes
  become_user: root

  vars_prompt:
    - name: docker_input
      prompt: "1) Setup Files\n2) Compose up\n3) Compose rm"
      private: False

  roles:
    - docker
...
