---
-
  hosts: localhost
  connection: local 
  gather_facts: false

  tasks:
    - name: Create a SG for SSH & HTTP access
      amazon.aws.ec2_security_group:
        profile: ec2man # make a prompt
        name: ansible
        description: Ansible SG
        region: us-east-1 # make a prompt
        vpc_id: vpc-031a4e8389dec4a3e # make a prompt
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0 
          - proto: tcp 
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Provision an instance
      amazon.aws.ec2_instance:
        profile: ec2man
        key_name: ansible
        instance_type: t2.micro # prompt
        image_id: ami-080e1f13689e07408 # prompt
        region: us-east-1
        wait: true
        exact_count: 2
        tags:
          Ansible: AnsibleNginxWebServers
      register: ec2 

    - name: Add all instance public IPs to host group
      ansible.builtin.add_host:
        hostname: "{{ item.public_ip_address }}"
        groups: ansiblehosts
      with_items: "{{ ec2.instances }}"

    - name: Show group
      debug:
        var: groups.ansiblehosts
...
