---
-
  hosts: localhost
  connection: local
  
  tasks:
   - name: Get Public IP
     amazon.aws.ec2_instance_info:
      aws_profile: test-ec2
      region: us-east-1
     register: result 

   - name: Get Info
     ansible.builtin.add_host:
        hostname: "{{ item.instance_id }}"
        groups: ansiblehosts
     with_items: "{{ result.instances }}"

   - name: Show groups
     debug:
      var: groups.ansiblehosts
...
