services:
  go-backend:
    #    image: 4b33b091a935
    container_name: go
    build:
      context: ../servers/go/
      dockerfile: Dockerfile
    ports:
      - "1234:1234"

  express-backend:
    #image: feb890d9439b
    container_name: express
    build:
      context: ../servers/express-js/
      dockerfile: Dockerfile
    ports:
      - "5678:5678"

  proxy:
    build:
      context: ../servers/proxy/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - go-backend
      - express-backend

  frontend:
    #image: d12758100786
    container_name: frontend
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - proxy