services:
  frontend:
    image: d12758100786
#    build:
#      context: ../frontend/
#      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  go-backend:
    image: 4b33b091a935
    container_name: go # for referencing inside the other containers
#    build:
#      context: ../servers/go/
#      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    depends_on:
      - frontend

  express-backend:
    image: feb890d9439b
    container_name: express
#    build:
#      context: ../servers/express-js/
#      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    depends_on:
      - frontend

  proxy:
    build:
      context: ../servers/proxy/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - go-backend # cant use container name here
      - express-backend
