---
apiVersion: v1
kind: Secret
metadata:
  name: ejsenv
  namespace: default
type: Opaque
data:
  SECRET: c2RmczY1MWRmMTVzZDQxZjE1ZHMxZjVkczFmNXNkMWZmd2VyZjFkc3MxZjU1ZWY2OQo=
  DATABASE_NAME: dXNlcl9kYgo=
  DATABASE_COLLECTION: dXNlcl9kYl91cmxzaG9ydGVuZXIK
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9hcm5hdjp1cmxzaG9ydGVuZXJAY2x1c3RlcjAuOGhscngwdS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
  REDIS_URI: cmVkaXMtMTE0MzAuYzExLnVzLWVhc3QtMS0zLmVjMi5jbG91ZC5yZWRpc2xhYnMuY29t
  REDIS_PASS: dzVZeVZVMG1GRExkVXZaQXNZVEg4RXg2Rm5HVjFYQms=
  ORIGINS: aHR0cDovLzE5Mi4xNjguNTguMjozMTUzNi8=
  NGINX_ENDPOINT: aHR0cDovLzE5Mi4xNjguNTguMjozMDM5NQ==
...