---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: ClusterIP
  selector:
    app: nextjs
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
...