apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: nextjs
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
      tier: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: nextjs
        tier: frontend
    spec:
      containers:
        - name: nextjs-frontend
          image: arnavneo/next-frontend:2.0
          ports:
            - name: http-frontend
              containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: http://192.168.58.2:30395/api
      restartPolicy: Always
      