---
- name: Getting the required files
  block:
    - name: Copying the script
      ansible.builtin.copy:
        src: get_files.sh
        dest: "{{ docker_script_dest }}"
        mode: '0644'
      register: copy_output
      when: docker_input == "1"

    - name: Running the script
      ansible.builtin.script: "{{ docker_script_dest }}get_files.sh {{ docker_github_token }}"
      register: script_result
      when: docker_input == "1"

    - name: Install pip
      command: sudo apt-get install python3-pip -y
      when: docker_input == "1"

    - name: Install docker python
      command: pip install docker==6.1.3 # only this works
      when: docker_input == "1"

    - name: Install docker-compose python package
      ansible.builtin.pip:
        name: docker-compose
      when: docker_input == "1"

- name: Debug Output
  ansible.builtin.debug:
    var:
      - copy_output
      - script_result
...
